# server configuration can be done inside rocket.toml

# makemkvcon_path = "custom path to makemkvcon"
# ffmpeg_path = "custom path to ffmpeg"

# devices to use
devices = [
  "/dev/sr0"
]

[keys]
tmdb = "your-key"
